config/routes.rb
Rails.application.routes.draw do
  resources :managers
  resources :lostbooks
  resources :textbooks
  devise_for :users
  resources :historyborrowtables
  resources :unaffirmedbooks
  resources :searches
  resources :materials
  resources :journals
  resources :damagebooks
  resources :borrowtables
  resources :books
  resources :students
  resources :textbooksearches
  root 'books#index'
  get '/statistics', to: "statistics#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  self.inheritance_column = "not_sti"
  enum category: [:文学,:计算机,:数学,:物理,:小说]



  def self.search(search)
    if search
      where(["title LIKE ?","%#{search}%"])
    else
      all
    end
  end


end

app/models/borrowtable.rb
class Borrowtable < ApplicationRecord
  belongs_to :student
end

app/models/damagebook.rb
class Damagebook < ApplicationRecord
  enum level: [:"1",:"2",:"3"]
end

app/models/journal.rb
class Journal < ApplicationRecord
  enum journaltype: [:文学,:计算机,:艺术,:时尚]
end

app/models/lostbook.rb
class Lostbook < ApplicationRecord
  belongs_to :student
end

app/models/manager.rb
class Manager < ApplicationRecord
  belongs_to :user

  enum gender: [:男,:女]
end

app/models/material.rb
class Material < ApplicationRecord
  enum departmentid: [:"01",:"02",:"03",:"04",:"05",:"06",:"07",:"08"]
end

app/models/search.rb
class Search < ApplicationRecord
  self.inheritance_column = "not_sti"

  def search_book
    book = Book.all

    book = book.where(['title LIKE ?', title]) if title.present?
    book = book.where(['author LIKE ?', author]) if author.present?
    book = book.where(['press LIKE ?', press]) if press.present?

    return book
  end
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :user
  has_many :borrowtables
  has_many :historyborrowtables
  has_many :lostbooks

  enum gender: [:男,:女]
  enum department: [:"01",:"02",:"03",:"04",:"05",:"06",:"07",:"08"]
end

app/models/textbook.rb
class Textbook < ApplicationRecord
  #enum department: [:"01",:"02",:"03",:"04",:"05",:"06",:"07",:"08"]
  #enum term: [:大一上,:大一下,:大二上,:大二下,:大三上,:大三下,:大四上,:大四下]
  self.inheritance_column = "not_sti"

  def self.search(search)
    if search
      where(["book LIKE ?","%#{search}%"])
    else
      all
    end
  end

end

app/models/textbooksearch.rb
class Textbooksearch < ApplicationRecord
  self.inheritance_column = "not_sti"

  def textbooksearch_textbook
    textbook = Textbook.all

    textbook = textbook.where(['bookname LIKE ?', bookname]) if bookname.present?
    textbook = textbook.where(['department LIKE ?', department]) if department.present?
    textbook = textbook.where(['term LIKE ?', term]) if term.present?

    return textbook
  end
end

app/models/unaffirmedbook.rb
class Unaffirmedbook < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, uniqueness: true
  validates :userid, uniqueness: true

  enum role: [:admin, :student, :superadmin]

  has_one :student
  has_one :manager


  def display_name
    if student?
      self.username + " (学生)"
    elsif admin?
      self.username + " (管理员)"
    else
      self.username
    end
  end


  def email_changed?
    false
  end

end

app/controllers/textbooks_controller.rb
class TextbooksController < ApplicationController
  before_action :set_textbook, only: [:show, :edit, :update, :destroy]

  # GET /textbooks
  # GET /textbooks.json
  def index
    @textbooks = Textbook.search(params[:search])
  end

  # GET /textbooks/1
  # GET /textbooks/1.json
  def show
  end

  # GET /textbooks/new
  def new
    @textbook = Textbook.new
  end

  # GET /textbooks/1/edit
  def edit
  end

  # POST /textbooks
  # POST /textbooks.json
  def create
    @textbook = Textbook.new(textbook_params)

    respond_to do |format|
      if @textbook.save
        format.html { redirect_to @textbook, notice: '成功添加教材！' }
        format.json { render :show, status: :created, location: @textbook }
      else
        format.html { render :new }
        format.json { render json: @textbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /textbooks/1
  # PATCH/PUT /textbooks/1.json
  def update
    respond_to do |format|
      if @textbook.update(textbook_params)
        format.html { redirect_to @textbook, notice: '教材信息更新成功！' }
        format.json { render :show, status: :ok, location: @textbook }
      else
        format.html { render :edit }
        format.json { render json: @textbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /textbooks/1
  # DELETE /textbooks/1.json
  def destroy
    @textbook.destroy
    respond_to do |format|
      format.html { redirect_to textbooks_url, notice: '成功删除教材信息！' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_textbook
      @textbook = Textbook.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def textbook_params
      params.require(:textbook).permit(:department, :term, :bookname, :author, :press)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/helpers/lostbooks_helper.rb
module LostbooksHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/textbooks_helper.rb
module TextbooksHelper
end

app/views/textbooks/_form.html.erb
<p></p>
<%= form_with(model: textbook, local: true) do |form| %>
  <% if textbook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(textbook.errors.count, "error") %> prohibited this textbook from being saved:</h2>

      <ul>
        <% textbook.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container p-3 my-3 border">
  <div class="form-group">
    <%= form.label :系号 %>
    <%= form.text_field :department ,{class:"form-control"} %>
  </div>

  <div class="form-group">
    <%= form.label :学期 %>
    <%= form.text_field :term ,{class:"form-control"} %>
  </div>

  <div class="form-group">
    <%= form.label :教材名 %>
    <%= form.text_field :bookname  ,{class:"form-control"}%>
  </div>

  <div class="form-group">
    <%= form.label :作者 %>
    <%= form.text_field :author ,{class:"form-control"} %>
  </div>

  <div class="form-group">
    <%= form.label :出版社 %>
    <%= form.text_field :press  ,{class:"form-control"}%>
  </div>

  <div class="actions">
    <%= form.submit "确认",class:"btn btn-primary"%>
  </div>
  </div>
<% end %>

app/views/textbooks/edit.html.erb
<p></p>
<h1>编辑教材信息</h1>

<%= render 'form', textbook: @textbook %>


<%= link_to '返回', textbooks_path %>

app/views/textbooks/index.html.erb
<p></p>
<h1>教材清单</h1>

<%= form_with(url: '/textbooks', method: 'get', local: true) do %>
  <%= text_field_tag(:search) %>
  <%= submit_tag("搜索",class:"btn btn-primary",style: "font-size:10px;font-weight:100px")%>
<% end %>
<%= link_to "高级检索", new_textbooksearch_path %>
<table class="table">
  <thead>
    <tr>
      <th>系号</th>
      <th>学期</th>
      <th>教材名称</th>
      <th>作者</th>
      <th>出版社</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @textbooks.each do |textbook| %>
      <tr>
        <td><%= textbook.department %></td>
        <td><%= textbook.term %></td>
        <td><%= textbook.bookname %></td>
        <td><%= textbook.author %></td>
        <td><%= textbook.press %></td>
        <% if current_user.admin? || current_user.superadmin?%>
          <td><%= link_to '编辑信息', edit_textbook_path(textbook),class: "btn btn-warning" ,style: "color:white;font-size:10px;font-weight:bold" %></td>
          <td><%= link_to '删除', textbook, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-danger" ,style: "color:white;font-size:10px;font-weight:bold" %></td>
        <% end %>
      </tr>
    <%end %>

  </tbody>
</table>

<br>
<% if user_signed_in? %>
<% if current_user.admin? || current_user.superadmin?%>
<%= link_to '新增教材', new_textbook_path,class: "btn btn-primary" ,style: "color:white"%>
<% end %>
<% end %>

app/views/textbooks/new.html.erb
<p></p>
<h1>新增教材</h1>

<%= render 'form', textbook: @textbook %>

<%= link_to '返回', textbooks_path %>

app/views/textbooks/show.html.erb
<p></p>
<li class="list-group-item">
  <strong>系号:</strong>
  <%= @textbook.department %>
</li>

<li class="list-group-item">
  <strong>学期:</strong>
  <%= @textbook.term %>
</li>

<li class="list-group-item">
  <strong>书名:</strong>
  <%= @textbook.bookname %>
</li>

<li class="list-group-item">
  <strong>作者:</strong>
  <%= @textbook.author %>
</li>

<li class="list-group-item">
  <strong>出版社:</strong>
  <%= @textbook.press %>
</li>
<p></p>
<%= link_to '返回', textbooks_path %>