config/routes.rb
Rails.application.routes.draw do
  resources :managers
  resources :lostbooks
  resources :textbooks
  devise_for :users
  resources :historyborrowtables
  resources :unaffirmedbooks
  resources :searches
  resources :materials
  resources :journals
  resources :damagebooks
  resources :borrowtables
  resources :books
  resources :students
  resources :textbooksearches
  root 'books#index'
  get '/statistics', to: "statistics#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  self.inheritance_column = "not_sti"
  enum category: [:文学,:计算机,:数学,:物理,:小说]



  def self.search(search)
    if search
      where(["title LIKE ?","%#{search}%"])
    else
      all
    end
  end


end

app/models/borrowtable.rb
class Borrowtable < ApplicationRecord
  belongs_to :student
end

app/models/damagebook.rb
class Damagebook < ApplicationRecord
  enum level: [:"1",:"2",:"3"]
end

app/models/journal.rb
class Journal < ApplicationRecord
  enum journaltype: [:文学,:计算机,:艺术,:时尚]
end

app/models/lostbook.rb
class Lostbook < ApplicationRecord
  belongs_to :student
end

app/models/manager.rb
class Manager < ApplicationRecord
  belongs_to :user

  enum gender: [:男,:女]
end

app/models/material.rb
class Material < ApplicationRecord
  enum departmentid: [:"01",:"02",:"03",:"04",:"05",:"06",:"07",:"08"]
end

app/models/search.rb
class Search < ApplicationRecord
  self.inheritance_column = "not_sti"

  def search_book
    book = Book.all

    book = book.where(['title LIKE ?', title]) if title.present?
    book = book.where(['author LIKE ?', author]) if author.present?
    book = book.where(['press LIKE ?', press]) if press.present?

    return book
  end
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :user
  has_many :borrowtables
  has_many :historyborrowtables
  has_many :lostbooks

  enum gender: [:男,:女]
  enum department: [:"01",:"02",:"03",:"04",:"05",:"06",:"07",:"08"]
end

app/models/textbook.rb
class Textbook < ApplicationRecord
  #enum department: [:"01",:"02",:"03",:"04",:"05",:"06",:"07",:"08"]
  #enum term: [:大一上,:大一下,:大二上,:大二下,:大三上,:大三下,:大四上,:大四下]
  self.inheritance_column = "not_sti"

  def self.search(search)
    if search
      where(["book LIKE ?","%#{search}%"])
    else
      all
    end
  end

end

app/models/textbooksearch.rb
class Textbooksearch < ApplicationRecord
  self.inheritance_column = "not_sti"

  def textbooksearch_textbook
    textbook = Textbook.all

    textbook = textbook.where(['bookname LIKE ?', bookname]) if bookname.present?
    textbook = textbook.where(['department LIKE ?', department]) if department.present?
    textbook = textbook.where(['term LIKE ?', term]) if term.present?

    return textbook
  end
end

app/models/unaffirmedbook.rb
class Unaffirmedbook < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, uniqueness: true
  validates :userid, uniqueness: true

  enum role: [:admin, :student, :superadmin]

  has_one :student
  has_one :manager


  def display_name
    if student?
      self.username + " (学生)"
    elsif admin?
      self.username + " (管理员)"
    else
      self.username
    end
  end


  def email_changed?
    false
  end

end

app/controllers/unaffirmedbooks_controller.rb
class UnaffirmedbooksController < ApplicationController
  before_action :set_unaffirmedbook, only: [:show, :edit, :update, :destroy]

  # GET /unaffirmedbooks
  # GET /unaffirmedbooks.json
  def index
    @unaffirmedbooks = Unaffirmedbook.all
  end

  # GET /unaffirmedbooks/1
  # GET /unaffirmedbooks/1.json
  def show
  end

  # GET /unaffirmedbooks/new
  def new
    @unaffirmedbook = Unaffirmedbook.new
  end

  # GET /unaffirmedbooks/1/edit
  def edit
  end

  # POST /unaffirmedbooks
  # POST /unaffirmedbooks.json
  def create
    @unaffirmedbook = Unaffirmedbook.new(unaffirmedbook_params)

    respond_to do |format|
      if @unaffirmedbook.save
        format.html { redirect_to @unaffirmedbook, notice: 'Unaffirmedbook was successfully created.' }
        format.json { render :show, status: :created, location: @unaffirmedbook }
      else
        format.html { render :new }
        format.json { render json: @unaffirmedbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /unaffirmedbooks/1
  # PATCH/PUT /unaffirmedbooks/1.json
  def update
    respond_to do |format|
      if @unaffirmedbook.update(unaffirmedbook_params)
        format.html { redirect_to @unaffirmedbook, notice: 'Unaffirmedbook was successfully updated.' }
        format.json { render :show, status: :ok, location: @unaffirmedbook }
      else
        format.html { render :edit }
        format.json { render json: @unaffirmedbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unaffirmedbooks/1
  # DELETE /unaffirmedbooks/1.json
  def destroy
    book_id = params[:book_id]
    book_title = params[:book_title]
    borrower_id = params[:borrower_id]
    overdue = params[:overdue]
    if overdue == "已逾期"
      student = Student.find(borrower_id)
      student.credit = student.credit - 5
      if student.credit < 0
        student.credit = 0
      end
      student.save!
    else
      student = Student.find(borrower_id)
      if student.credit < 100
      student.credit = student.credit + 2 > 100 ? 100 : student.credit + 2
      student.save!
      end
    end


    historyborrowtable = Historyborrowtable.where(["bookid = ?", book_id]).last
    historyborrowtable.returndate = Date.today
    historyborrowtable.save!

    book = Book.find(book_id)
    book.state = "未借阅"
    book.save!

    @unaffirmedbook.destroy
    respond_to do |format|
      format.html { redirect_to unaffirmedbooks_url, notice: '操作成功' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unaffirmedbook
      @unaffirmedbook = Unaffirmedbook.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def unaffirmedbook_params
      params.require(:unaffirmedbook).permit(:bookid, :booktitle, :expected_return, :returndate, :overdue)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/helpers/lostbooks_helper.rb
module LostbooksHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/textbooks_helper.rb
module TextbooksHelper
end

app/helpers/unaffirmedbooks_helper.rb
module UnaffirmedbooksHelper
end

app/views/unaffirmedbooks/_form.html.erb
<%= form_with(model: unaffirmedbook, local: true) do |form| %>
  <% if unaffirmedbook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(unaffirmedbook.errors.count, "error") %> prohibited this unaffirmedbook from being saved:</h2>

      <ul>
        <% unaffirmedbook.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :bookid %>
    <%= form.text_field :bookid %>
  </div>

  <div class="field">
    <%= form.label :booktitle %>
    <%= form.text_field :booktitle %>
  </div>

  <div class="field">
    <%= form.label :expected_return %>
    <%= form.text_field :expected_return %>
  </div>

  <div class="field">
    <%= form.label :returndate %>
    <%= form.text_field :returndate %>
  </div>

  <div class="field">
    <%= form.label :overdue %>
    <%= form.text_field :overdue %>
  </div>

  <div class="actions">
    <%= form.submit "确认"%>
  </div>
<% end %>

app/views/unaffirmedbooks/edit.html.erb
<h1>Editing Unaffirmedbook</h1>

<%= render 'form', unaffirmedbook: @unaffirmedbook %>

<%= link_to 'Show', @unaffirmedbook %> |
<%= link_to 'Back', unaffirmedbooks_path %>

app/views/unaffirmedbooks/index.html.erb
<p >

</p>
<h1>待确认图书</h1>

<table class="table">
  <thead>
    <tr>
      <th>图书编号</th>
      <th>书名</th>
      <th>借阅者学号</th>
      <th>规定归还日期</th>
      <th>实际归还日期</th>
      <th>是否逾期</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @unaffirmedbooks.each do |unaffirmedbook| %>
      <tr>
        <td><%= unaffirmedbook.bookid %></td>
        <td><%= unaffirmedbook.booktitle %></td>
        <td><%= unaffirmedbook.borrowerid %></td>
        <td><%= unaffirmedbook.expected_return %></td>
        <td><%= unaffirmedbook.returndate %></td>
        <td><%= unaffirmedbook.overdue %></td>
        <td><%= link_to '确认归还', unaffirmedbook_path(id: unaffirmedbook.id, book_id: unaffirmedbook.bookid,book_title: unaffirmedbook.booktitle,
                                                    overdue: unaffirmedbook.overdue, borrower_id: unaffirmedbook.borrowerid),
                        method: :delete, data: { confirm: '确定还书？'},class: "btn btn-success",style: "color: white;font-size:10px;font-weight:bold"  %></td>
        <td><%= link_to '图书损坏', new_damagebook_path(:book_id => unaffirmedbook.bookid, :book_title => unaffirmedbook.booktitle,
                :borrower_id => unaffirmedbook.borrowerid) ,class: "btn btn-danger" ,style: "color:white;font-size:10px;font-weight:bold"%></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/unaffirmedbooks/new.html.erb
<h1>New Unaffirmedbook</h1>

<%= render 'form', unaffirmedbook: @unaffirmedbook %>

<%= link_to 'Back', unaffirmedbooks_path %>

app/views/unaffirmedbooks/show.html.erb
<p>
  <strong>Bookid:</strong>
  <%= @unaffirmedbook.bookid %>
</p>

<p>
  <strong>Booktitle:</strong>
  <%= @unaffirmedbook.booktitle %>
</p>

<p>
  <strong>Expected return:</strong>
  <%= @unaffirmedbook.expected_return %>
</p>

<p>
  <strong>Returndate:</strong>
  <%= @unaffirmedbook.returndate %>
</p>

<p>
  <strong>Overdue:</strong>
  <%= @unaffirmedbook.overdue %>
</p>

<%= link_to 'Edit', edit_unaffirmedbook_path(@unaffirmedbook) %> |
<%= link_to 'Back', unaffirmedbooks_path %>