config/routes.rb
Rails.application.routes.draw do
  resources :managers
  resources :lostbooks
  resources :textbooks
  devise_for :users
  resources :historyborrowtables
  resources :unaffirmedbooks
  resources :searches
  resources :materials
  resources :journals
  resources :damagebooks
  resources :borrowtables
  resources :books
  resources :students
  resources :textbooksearches
  root 'books#index'
  get '/statistics', to: "statistics#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  self.inheritance_column = "not_sti"
  enum category: [:文学,:计算机,:数学,:物理,:小说]



  def self.search(search)
    if search
      where(["title LIKE ?","%#{search}%"])
    else
      all
    end
  end


end

app/models/borrowtable.rb
class Borrowtable < ApplicationRecord
  belongs_to :student
end

app/models/damagebook.rb
class Damagebook < ApplicationRecord
  enum level: [:"1",:"2",:"3"]
end

app/models/journal.rb
class Journal < ApplicationRecord
  enum journaltype: [:文学,:计算机,:艺术,:时尚]
end

app/models/lostbook.rb
class Lostbook < ApplicationRecord
  belongs_to :student
end

app/models/manager.rb
class Manager < ApplicationRecord
  belongs_to :user

  enum gender: [:男,:女]
end

app/models/material.rb
class Material < ApplicationRecord
  enum departmentid: [:"01",:"02",:"03",:"04",:"05",:"06",:"07",:"08"]
end

app/models/search.rb
class Search < ApplicationRecord
  self.inheritance_column = "not_sti"

  def search_book
    book = Book.all

    book = book.where(['title LIKE ?', title]) if title.present?
    book = book.where(['author LIKE ?', author]) if author.present?
    book = book.where(['press LIKE ?', press]) if press.present?

    return book
  end
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :user
  has_many :borrowtables
  has_many :historyborrowtables
  has_many :lostbooks

  enum gender: [:男,:女]
  enum department: [:"01",:"02",:"03",:"04",:"05",:"06",:"07",:"08"]
end

app/models/textbook.rb
class Textbook < ApplicationRecord
  #enum department: [:"01",:"02",:"03",:"04",:"05",:"06",:"07",:"08"]
  #enum term: [:大一上,:大一下,:大二上,:大二下,:大三上,:大三下,:大四上,:大四下]
  self.inheritance_column = "not_sti"

  def self.search(search)
    if search
      where(["book LIKE ?","%#{search}%"])
    else
      all
    end
  end

end

app/models/textbooksearch.rb
class Textbooksearch < ApplicationRecord
  self.inheritance_column = "not_sti"

  def textbooksearch_textbook
    textbook = Textbook.all

    textbook = textbook.where(['bookname LIKE ?', bookname]) if bookname.present?
    textbook = textbook.where(['department LIKE ?', department]) if department.present?
    textbook = textbook.where(['term LIKE ?', term]) if term.present?

    return textbook
  end
end

app/models/unaffirmedbook.rb
class Unaffirmedbook < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, uniqueness: true
  validates :userid, uniqueness: true

  enum role: [:admin, :student, :superadmin]

  has_one :student
  has_one :manager


  def display_name
    if student?
      self.username + " (学生)"
    elsif admin?
      self.username + " (管理员)"
    else
      self.username
    end
  end


  def email_changed?
    false
  end

end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
  before_action :set_manager, only: [:show, :edit, :update, :destroy]

  # GET /managers
  # GET /managers.json
  def index
    @managers = Manager.all
  end

  # GET /managers/1
  # GET /managers/1.json
  def show
  end

  # GET /managers/new
  def new
    @manager = Manager.new
  end

  # GET /managers/1/edit
  def edit
  end

  # POST /managers
  # POST /managers.json
  def create
    @manager = Manager.new(manager_params)
    id = manager_params[:managerid]
    email = manager_params[:email]
    name = manager_params[:name]
    password = "123456"
    user = User.new(:email => email, :userid => id, :password => password, :password_confirmation => password,
                    :role => "admin", :username => name)
    user.save!

    @manager.user = user

    respond_to do |format|
      if @manager.save
        format.html { redirect_to @manager, notice: 'Manager was successfully created.' }
        format.json { render :show, status: :created, location: @manager }
      else
        format.html { render :new }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /managers/1
  # PATCH/PUT /managers/1.json
  def update
    respond_to do |format|
      if @manager.update(manager_params)
        format.html { redirect_to @manager, notice: 'Manager was successfully updated.' }
        format.json { render :show, status: :ok, location: @manager }
      else
        format.html { render :edit }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /managers/1
  # DELETE /managers/1.json
  def destroy
    @manager.destroy
    respond_to do |format|
      format.html { redirect_to managers_url, notice: 'Manager was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manager
      @manager = Manager.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def manager_params
      params.require(:manager).permit(:name, :managerid, :gender, :phone, :email)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/helpers/lostbooks_helper.rb
module LostbooksHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/textbooks_helper.rb
module TextbooksHelper
end

app/views/managers/_form.html.erb
<%= form_with(model: manager, local: true) do |form| %>
  <% if manager.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(manager.errors.count, "error") %> prohibited this manager from being saved:</h2>

      <ul>
        <% manager.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container p-3 my-3 border">
  <div class="form-group">
    <%= form.label :管理员ID %>
    <%= form.text_field :managerid ,{class:"form-control"} %>
  </div>

  <div class="form-group">
    <%= form.label :姓名 %>
    <%= form.text_field :name  ,{class:"form-control"}%>
  </div>

  <div class="form-group">
    <%= form.label :性别 %>
    <%= form.collection_select :gender,Manager.genders.map { |a|
      [a.first,a.first]}, :first, :second ,{class:"form-control"} %>
  </div>

  <div class="form-group">
    <%= form.label :联系电话 %>
    <%= form.text_field :phone  ,{class:"form-control"}%>
  </div>

  <div class="form-group">
    <%= form.label :电子邮箱 %>
    <%= form.text_field :email  ,{class:"form-control"}%>
  </div>

  <div class="actions">
    <%= form.submit "确认",class:"btn btn-primary"%>
  </div>
<% end %>
</div>

app/views/managers/edit.html.erb
<p></p>
<h1>编辑管理员信息</h1>

<%= render 'form', manager: @manager %>

<p></p>
<%= link_to '返回', managers_path %>

app/views/managers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>管理员信息</h1>

<table class="table">
  <thead>
    <tr>
      <th>管理员ID</th>
      <th>姓名</th>
      <th>性别</th>
      <th>联系电话</th>
      <th>电子邮箱</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @managers.each do |manager| %>
      <tr>
        <td><%= manager.managerid %></td>
        <td><%= manager.name %></td>
        <td><%= manager.gender %></td>
        <td><%= manager.phone %></td>
        <td><%= manager.email %></td>
        <% if user_signed_in? %>
          <% if current_user.superadmin? %>
        <td><%= link_to '编辑信息', edit_manager_path(manager),class: "btn btn-warning" ,style: "font-size:10px;font-weight:bold"%></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
<% if current_user.superadmin? %>
<%= link_to '新增管理员', new_manager_path ,class: "btn btn-primary",style: "color:white"%>
<% end %>
<% end %>

app/views/managers/new.html.erb
<p></p>
<h1>新增管理员</h1>

<%= render 'form', manager: @manager %>
<p></p>
<%= link_to '返回', managers_path %>

app/views/managers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @manager.name %>
</p>

<p>
  <strong>Managerid:</strong>
  <%= @manager.managerid %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @manager.gender %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @manager.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @manager.email %>
</p>

<%= link_to 'Edit', edit_manager_path(@manager) %> |
<%= link_to 'Back', managers_path %>