config/routes.rb
Rails.application.routes.draw do
  resources :managers
  resources :lostbooks
  resources :textbooks
  devise_for :users
  resources :historyborrowtables
  resources :unaffirmedbooks
  resources :searches
  resources :materials
  resources :journals
  resources :damagebooks
  resources :borrowtables
  resources :books
  resources :students
  resources :textbooksearches
  root 'books#index'
  get '/statistics', to: "statistics#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  self.inheritance_column = "not_sti"
  enum category: [:文学,:计算机,:数学,:物理,:小说]



  def self.search(search)
    if search
      where(["title LIKE ?","%#{search}%"])
    else
      all
    end
  end


end

app/models/borrowtable.rb
class Borrowtable < ApplicationRecord
  belongs_to :student
end

app/models/damagebook.rb
class Damagebook < ApplicationRecord
  enum level: [:"1",:"2",:"3"]
end

app/models/journal.rb
class Journal < ApplicationRecord
  enum journaltype: [:文学,:计算机,:艺术,:时尚]
end

app/models/lostbook.rb
class Lostbook < ApplicationRecord
  belongs_to :student
end

app/models/manager.rb
class Manager < ApplicationRecord
  belongs_to :user

  enum gender: [:男,:女]
end

app/models/material.rb
class Material < ApplicationRecord
  enum departmentid: [:"01",:"02",:"03",:"04",:"05",:"06",:"07",:"08"]
end

app/models/search.rb
class Search < ApplicationRecord
  self.inheritance_column = "not_sti"

  def search_book
    book = Book.all

    book = book.where(['title LIKE ?', title]) if title.present?
    book = book.where(['author LIKE ?', author]) if author.present?
    book = book.where(['press LIKE ?', press]) if press.present?

    return book
  end
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :user
  has_many :borrowtables
  has_many :historyborrowtables
  has_many :lostbooks

  enum gender: [:男,:女]
  enum department: [:"01",:"02",:"03",:"04",:"05",:"06",:"07",:"08"]
end

app/models/textbook.rb
class Textbook < ApplicationRecord
  #enum department: [:"01",:"02",:"03",:"04",:"05",:"06",:"07",:"08"]
  #enum term: [:大一上,:大一下,:大二上,:大二下,:大三上,:大三下,:大四上,:大四下]
  self.inheritance_column = "not_sti"

  def self.search(search)
    if search
      where(["book LIKE ?","%#{search}%"])
    else
      all
    end
  end

end

app/models/textbooksearch.rb
class Textbooksearch < ApplicationRecord
  self.inheritance_column = "not_sti"

  def textbooksearch_textbook
    textbook = Textbook.all

    textbook = textbook.where(['bookname LIKE ?', bookname]) if bookname.present?
    textbook = textbook.where(['department LIKE ?', department]) if department.present?
    textbook = textbook.where(['term LIKE ?', term]) if term.present?

    return textbook
  end
end

app/models/unaffirmedbook.rb
class Unaffirmedbook < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, uniqueness: true
  validates :userid, uniqueness: true

  enum role: [:admin, :student, :superadmin]

  has_one :student
  has_one :manager


  def display_name
    if student?
      self.username + " (学生)"
    elsif admin?
      self.username + " (管理员)"
    else
      self.username
    end
  end


  def email_changed?
    false
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_search, only: [:show, :edit, :update, :destroy]

  # GET /searches
  # GET /searches.json
  def index
    @searches = Search.all
  end

  # GET /searches/1
  # GET /searches/1.json
  def show
    @search = Search.find(params[:id])
  end

  # GET /searches/new
  def new
    @search = Search.new
    @authors = Book.distinct.pluck(:author)
    @presses = Book.distinct.pluck(:press)
  end

  # GET /searches/1/edit
  def edit
  end

  # POST /searches
  # POST /searches.json
  def create
    @search = Search.create(search_params)
    redirect_to @search
  end

  # PATCH/PUT /searches/1
  # PATCH/PUT /searches/1.json
  def update
    respond_to do |format|
      if @search.update(search_params)
        format.html { redirect_to @search, notice: 'Search was successfully updated.' }
        format.json { render :show, status: :ok, location: @search }
      else
        format.html { render :edit }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /searches/1
  # DELETE /searches/1.json
  def destroy
    @search.destroy
    respond_to do |format|
      format.html { redirect_to searches_url, notice: 'Search was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_search
      @search = Search.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def search_params
      params.require(:search).permit(:title, :author, :press)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/helpers/lostbooks_helper.rb
module LostbooksHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/textbooks_helper.rb
module TextbooksHelper
end

app/views/searches/_form.html.erb
<%= form_with(model: search, local: true) do |form| %>
  <% if search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
        <% search.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :press %>
    <%= form.text_field :press %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/searches/edit.html.erb
<h1>Editing Search</h1>

<%= render 'form', search: @search %>

<%= link_to 'Show', @search %> |
<%= link_to 'Back', searches_path %>

app/views/searches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Searches</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Press</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @searches.each do |search| %>
      <tr>
        <td><%= search.title %></td>
        <td><%= search.author %></td>
        <td><%= search.press %></td>
        <td><%= link_to 'Show', search %></td>
        <td><%= link_to 'Edit', edit_search_path(search) %></td>
        <td><%= link_to 'Destroy', search, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Search', new_search_path %>

app/views/searches/new.html.erb
<h1>高级检索</h1>
<div class="container p-3 my-3 border">
<%= form_with model: @search do |f| %>
    <div class="form-group">
      <%= f.label :书名 %>
      <%= f.text_field :title %>
    </div>

    <div class="form-group">
      <%= f.label :作者 %>
      <%= f.select :author, options_for_select(@authors), include_blank: true %><br>
    </div>

    <div class="form-group">
      <%= f.label :出版社 %>
      <%= f.select :press, options_for_select(@presses), include_blank: true %><br><br>
    </div>

    <div class="actions">
      <%= f.submit "搜索" ,class:"btn btn-primary"%>
    </div>


<% end %>
</div>
<p><%= link_to "返回", '/books' %></p>

app/views/searches/show.html.erb
<h1>搜索结果</h1>

<% if @search.search_book.empty? %>
  <p>No book were found.</p>
<% else %>
  <table class="table">
    <thead>
    <tr>
      <th>图书编号</th>
      <th>书名</th>
      <th>作者</th>
      <th>出版社</th>
      <th>价格</th>
      <th>入库日期</th>
      <th>图书类别</th>
      <th>图书状态</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @search.search_book.each do |book| %>
      <tr>
        <td><%= book.id %></td>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.press %></td>
        <td><%= book.price %></td>
        <td><%= book.intime %></td>
        <td><%= book.category %></td>
        <td><%= book.state %></td>
        <td><%= link_to '详细信息', book,class: "btn btn-success",style: "color: white;font-size:10px;font-weight:bold" %></td>
        <% if current_user.admin? %>
          <td><%= link_to '编辑信息', edit_book_path(book) ,class: "btn btn-warning" ,style: "color:white;font-size:10px;font-weight:bold"%></td>
          <td><%= link_to '删除', book, method: :delete, data: { confirm: '确定删除图书?'},class: "btn btn-danger" ,style: "color:white;font-size:10px;font-weight:bold" %></td>
        <% end %>

        <% if current_user.student? %>
          <% if book.state == "已借阅" || book.state == "已损坏" || book.state == "丢失"%>
            <td><%= "暂时无法借阅" %></td>
          <% else %>
            <% if current_user.student.credit < 60 %>
              <td><%= "信用分过低" %></td>
            <% else %>
              <td><%= link_to '借阅本书', new_borrowtable_path(:book_id => book.id, :book_title => book.title),class: "btn btn-primary",style: "color:white;font-size:10px;font-weight:bold" %></td>
            <% end %>
          <% end %>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

<br>
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <p><%= link_to "返回", new_search_path %></p>
  <% end %>
<% end %>